AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  boundless-sales-notifier

  Monitoring tool for Boundless shop stands

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  DiscordWebhookStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachines/discord-webhook.asl.json
      DefinitionSubstitutions:
        DiscordCheckWebhookFunctionArn: !GetAtt DiscordCheckWebhookFunction.Arn
        DiscordPostMessageFunctionArn: !GetAtt DiscordPostMessageFunction.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref DiscordCheckWebhookFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref DiscordPostMessageFunction
  ButtBeaconScannerStateMachine:
    Type: AWS::Serverless::StateMachine # More info about State Machine Resource: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-statemachine.html
    Properties:
      DefinitionUri: statemachines/butt-beacon-scanner.asl.json
      DefinitionSubstitutions:
        ButtRetrieveStockFromAPIFunctionArn: !GetAtt ButtRetrieveStockFromAPIFunction.Arn
        CompareStockWithLastRunFunctionArn: !GetAtt CompareStockWithLastRunFunction.Arn
        PLACEHOLDERFUNCTION: !GetAtt PlaceholderFunction.Arn
      Policies: # Find out more about SAM policy templates: https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html
        - LambdaInvokePolicy:
            FunctionName: !Ref ButtRetrieveStockFromAPIFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref CompareStockWithLastRunFunction
        - LambdaInvokePolicy:
            FunctionName: !Ref PlaceholderFunction

  ButtRetrieveStockFromAPIFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/butt/retrieve-stock/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x

  CompareStockWithLastRunFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/butt/compare-stock/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Environment:
        Variables:
          tablename: !Ref ShopStockTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ShopStockTable

  DiscordCheckWebhookFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/discord/check-webhook/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x

  DiscordPostMessageFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/discord/post-message/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x

  PlaceholderFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: functions/placeholder/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x

  ShopStockTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: "beacon"
          AttributeType: "S"
        - AttributeName: "item_id"
          AttributeType: "N"
      KeySchema:
        - AttributeName: "beacon"
          KeyType: "HASH"
        - AttributeName: "item_id"
          KeyType: "RANGE"
      ProvisionedThroughput:
        WriteCapacityUnits: 1
        ReadCapacityUnits: 1

Outputs:
  ButtBeaconScannerStateMachineArn:
    Description: "Discord Webhook State Machine ARN"
    Value: !Ref ButtBeaconScannerStateMachine
  ButtBeaconScannerStateMachineRole:
    Description: "Implicit IAM Role created for Discord Webhook State Machine"
    Value: !GetAtt ButtBeaconScannerStateMachineRole.Arn
